# Generated by cloudcoil-model-codegen; DO NOT EDIT
from importlib import import_module
from typing import TYPE_CHECKING, Literal, overload

from cloudcoil.resources import Resource

if TYPE_CHECKING:
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v1 import (
        CompositeResourceDefinition as _Resource1,
    )
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v1 import Composition as _Resource3
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v1 import (
        CompositionRevision as _Resource4,
    )
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v1alpha1 import (
        ManagedResourceActivationPolicy as _Resource16,
    )
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v1alpha1 import (
        ManagedResourceDefinition as _Resource17,
    )
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v1alpha1 import (
        Usage as _Resource21,
    )
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v1beta1 import (
        EnvironmentConfig as _Resource9,
    )
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v1beta1 import Usage as _Resource22
    from cloudcoil.models.crossplane.apiextensions_crossplane_io.v2 import (
        CompositeResourceDefinition as _Resource2,
    )
    from cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1 import CronOperation as _Resource7
    from cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1 import Operation as _Resource18
    from cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1 import WatchOperation as _Resource24
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1 import Configuration as _Resource5
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1 import ConfigurationRevision as _Resource6
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1 import Function as _Resource10
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1 import FunctionRevision as _Resource12
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1 import Provider as _Resource19
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1 import ProviderRevision as _Resource20
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1 import (
        DeploymentRuntimeConfig as _Resource8,
    )
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1 import Function as _Resource11
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1 import (
        FunctionRevision as _Resource13,
    )
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1 import ImageConfig as _Resource14
    from cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1 import Lock as _Resource15
    from cloudcoil.models.crossplane.protection_crossplane_io.v1beta1 import (
        ClusterUsage as _Resource0,
    )
    from cloudcoil.models.crossplane.protection_crossplane_io.v1beta1 import Usage as _Resource23

_MODELS = {
    ("ClusterUsage", "protection.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.protection_crossplane_io.v1beta1",
        "ClusterUsage",
    ),
    ("ClusterUsage", ""): (
        "cloudcoil.models.crossplane.protection_crossplane_io.v1beta1",
        "ClusterUsage",
    ),
    ("CompositeResourceDefinition", "apiextensions.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1",
        "CompositeResourceDefinition",
    ),
    ("CompositeResourceDefinition", "apiextensions.crossplane.io/v2"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v2",
        "CompositeResourceDefinition",
    ),
    ("Composition", "apiextensions.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1",
        "Composition",
    ),
    ("Composition", ""): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1",
        "Composition",
    ),
    ("CompositionRevision", "apiextensions.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1",
        "CompositionRevision",
    ),
    ("CompositionRevision", ""): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1",
        "CompositionRevision",
    ),
    ("Configuration", "pkg.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1",
        "Configuration",
    ),
    ("Configuration", ""): ("cloudcoil.models.crossplane.pkg_crossplane_io.v1", "Configuration"),
    ("ConfigurationRevision", "pkg.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1",
        "ConfigurationRevision",
    ),
    ("ConfigurationRevision", ""): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1",
        "ConfigurationRevision",
    ),
    ("CronOperation", "ops.crossplane.io/v1alpha1"): (
        "cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1",
        "CronOperation",
    ),
    ("CronOperation", ""): (
        "cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1",
        "CronOperation",
    ),
    ("DeploymentRuntimeConfig", "pkg.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1",
        "DeploymentRuntimeConfig",
    ),
    ("DeploymentRuntimeConfig", ""): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1",
        "DeploymentRuntimeConfig",
    ),
    ("EnvironmentConfig", "apiextensions.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1beta1",
        "EnvironmentConfig",
    ),
    ("EnvironmentConfig", ""): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1beta1",
        "EnvironmentConfig",
    ),
    ("Function", "pkg.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1",
        "Function",
    ),
    ("Function", "pkg.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1",
        "Function",
    ),
    ("FunctionRevision", "pkg.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1",
        "FunctionRevision",
    ),
    ("FunctionRevision", "pkg.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1",
        "FunctionRevision",
    ),
    ("ImageConfig", "pkg.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1",
        "ImageConfig",
    ),
    ("ImageConfig", ""): ("cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1", "ImageConfig"),
    ("Lock", "pkg.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1",
        "Lock",
    ),
    ("Lock", ""): ("cloudcoil.models.crossplane.pkg_crossplane_io.v1beta1", "Lock"),
    ("ManagedResourceActivationPolicy", "apiextensions.crossplane.io/v1alpha1"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1alpha1",
        "ManagedResourceActivationPolicy",
    ),
    ("ManagedResourceActivationPolicy", ""): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1alpha1",
        "ManagedResourceActivationPolicy",
    ),
    ("ManagedResourceDefinition", "apiextensions.crossplane.io/v1alpha1"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1alpha1",
        "ManagedResourceDefinition",
    ),
    ("ManagedResourceDefinition", ""): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1alpha1",
        "ManagedResourceDefinition",
    ),
    ("Operation", "ops.crossplane.io/v1alpha1"): (
        "cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1",
        "Operation",
    ),
    ("Operation", ""): ("cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1", "Operation"),
    ("Provider", "pkg.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1",
        "Provider",
    ),
    ("Provider", ""): ("cloudcoil.models.crossplane.pkg_crossplane_io.v1", "Provider"),
    ("ProviderRevision", "pkg.crossplane.io/v1"): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1",
        "ProviderRevision",
    ),
    ("ProviderRevision", ""): (
        "cloudcoil.models.crossplane.pkg_crossplane_io.v1",
        "ProviderRevision",
    ),
    ("Usage", "apiextensions.crossplane.io/v1alpha1"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1alpha1",
        "Usage",
    ),
    ("Usage", "apiextensions.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.apiextensions_crossplane_io.v1beta1",
        "Usage",
    ),
    ("Usage", "protection.crossplane.io/v1beta1"): (
        "cloudcoil.models.crossplane.protection_crossplane_io.v1beta1",
        "Usage",
    ),
    ("WatchOperation", "ops.crossplane.io/v1alpha1"): (
        "cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1",
        "WatchOperation",
    ),
    ("WatchOperation", ""): (
        "cloudcoil.models.crossplane.ops_crossplane_io.v1alpha1",
        "WatchOperation",
    ),
}


@overload
def get_model(
    kind: Literal["ClusterUsage"], *, api_version: Literal["protection.crossplane.io/v1beta1"]
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["ClusterUsage"], *, api_version: Literal[""] = ""
) -> type[_Resource0]: ...


@overload
def get_model(
    kind: Literal["CompositeResourceDefinition"],
    *,
    api_version: Literal["apiextensions.crossplane.io/v1"],
) -> type[_Resource1]: ...


@overload
def get_model(
    kind: Literal["CompositeResourceDefinition"],
    *,
    api_version: Literal["apiextensions.crossplane.io/v2"],
) -> type[_Resource2]: ...


@overload
def get_model(
    kind: Literal["Composition"], *, api_version: Literal["apiextensions.crossplane.io/v1"]
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["Composition"], *, api_version: Literal[""] = ""
) -> type[_Resource3]: ...


@overload
def get_model(
    kind: Literal["CompositionRevision"], *, api_version: Literal["apiextensions.crossplane.io/v1"]
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["CompositionRevision"], *, api_version: Literal[""] = ""
) -> type[_Resource4]: ...


@overload
def get_model(
    kind: Literal["Configuration"], *, api_version: Literal["pkg.crossplane.io/v1"]
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["Configuration"], *, api_version: Literal[""] = ""
) -> type[_Resource5]: ...


@overload
def get_model(
    kind: Literal["ConfigurationRevision"], *, api_version: Literal["pkg.crossplane.io/v1"]
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["ConfigurationRevision"], *, api_version: Literal[""] = ""
) -> type[_Resource6]: ...


@overload
def get_model(
    kind: Literal["CronOperation"], *, api_version: Literal["ops.crossplane.io/v1alpha1"]
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["CronOperation"], *, api_version: Literal[""] = ""
) -> type[_Resource7]: ...


@overload
def get_model(
    kind: Literal["DeploymentRuntimeConfig"], *, api_version: Literal["pkg.crossplane.io/v1beta1"]
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["DeploymentRuntimeConfig"], *, api_version: Literal[""] = ""
) -> type[_Resource8]: ...


@overload
def get_model(
    kind: Literal["EnvironmentConfig"],
    *,
    api_version: Literal["apiextensions.crossplane.io/v1beta1"],
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["EnvironmentConfig"], *, api_version: Literal[""] = ""
) -> type[_Resource9]: ...


@overload
def get_model(
    kind: Literal["Function"], *, api_version: Literal["pkg.crossplane.io/v1"]
) -> type[_Resource10]: ...


@overload
def get_model(
    kind: Literal["Function"], *, api_version: Literal["pkg.crossplane.io/v1beta1"]
) -> type[_Resource11]: ...


@overload
def get_model(
    kind: Literal["FunctionRevision"], *, api_version: Literal["pkg.crossplane.io/v1"]
) -> type[_Resource12]: ...


@overload
def get_model(
    kind: Literal["FunctionRevision"], *, api_version: Literal["pkg.crossplane.io/v1beta1"]
) -> type[_Resource13]: ...


@overload
def get_model(
    kind: Literal["ImageConfig"], *, api_version: Literal["pkg.crossplane.io/v1beta1"]
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["ImageConfig"], *, api_version: Literal[""] = ""
) -> type[_Resource14]: ...


@overload
def get_model(
    kind: Literal["Lock"], *, api_version: Literal["pkg.crossplane.io/v1beta1"]
) -> type[_Resource15]: ...


@overload
def get_model(kind: Literal["Lock"], *, api_version: Literal[""] = "") -> type[_Resource15]: ...


@overload
def get_model(
    kind: Literal["ManagedResourceActivationPolicy"],
    *,
    api_version: Literal["apiextensions.crossplane.io/v1alpha1"],
) -> type[_Resource16]: ...


@overload
def get_model(
    kind: Literal["ManagedResourceActivationPolicy"], *, api_version: Literal[""] = ""
) -> type[_Resource16]: ...


@overload
def get_model(
    kind: Literal["ManagedResourceDefinition"],
    *,
    api_version: Literal["apiextensions.crossplane.io/v1alpha1"],
) -> type[_Resource17]: ...


@overload
def get_model(
    kind: Literal["ManagedResourceDefinition"], *, api_version: Literal[""] = ""
) -> type[_Resource17]: ...


@overload
def get_model(
    kind: Literal["Operation"], *, api_version: Literal["ops.crossplane.io/v1alpha1"]
) -> type[_Resource18]: ...


@overload
def get_model(
    kind: Literal["Operation"], *, api_version: Literal[""] = ""
) -> type[_Resource18]: ...


@overload
def get_model(
    kind: Literal["Provider"], *, api_version: Literal["pkg.crossplane.io/v1"]
) -> type[_Resource19]: ...


@overload
def get_model(kind: Literal["Provider"], *, api_version: Literal[""] = "") -> type[_Resource19]: ...


@overload
def get_model(
    kind: Literal["ProviderRevision"], *, api_version: Literal["pkg.crossplane.io/v1"]
) -> type[_Resource20]: ...


@overload
def get_model(
    kind: Literal["ProviderRevision"], *, api_version: Literal[""] = ""
) -> type[_Resource20]: ...


@overload
def get_model(
    kind: Literal["Usage"], *, api_version: Literal["apiextensions.crossplane.io/v1alpha1"]
) -> type[_Resource21]: ...


@overload
def get_model(
    kind: Literal["Usage"], *, api_version: Literal["apiextensions.crossplane.io/v1beta1"]
) -> type[_Resource22]: ...


@overload
def get_model(
    kind: Literal["Usage"], *, api_version: Literal["protection.crossplane.io/v1beta1"]
) -> type[_Resource23]: ...


@overload
def get_model(
    kind: Literal["WatchOperation"], *, api_version: Literal["ops.crossplane.io/v1alpha1"]
) -> type[_Resource24]: ...


@overload
def get_model(
    kind: Literal["WatchOperation"], *, api_version: Literal[""] = ""
) -> type[_Resource24]: ...


@overload
def get_model(kind: str, *, api_version: str = "") -> type[Resource]: ...


def get_model(kind: str, *, api_version: str = "") -> type[Resource]:
    """Look up a model in this package; specify api_version for ambiguous kinds."""
    try:
        module, name = _MODELS[kind, api_version]
    except KeyError:
        raise ValueError(
            f"Unknown or ambiguous resource {kind!r}; specify a supported api_version"
        ) from None
    return getattr(import_module(module), name)
