# Generated by cloudcoil-model-codegen v0.7.1
# DO NOT EDIT

from typing import (
    Annotated,
    Any,
    Callable,
    ClassVar,
    Literal,
    overload,
)

from cloudcoil.apimachinery import ObjectMeta
from cloudcoil.pydantic import (
    UNSET,
    BaseModel,
    BaseModelBuilder,
    BuilderContextBase,
    GenericListBuilder,
    ListBuilderContext,
    Never,
    Self,
)
from cloudcoil.resources import Resource
from pydantic import AwareDatetime, Field


class EnvironmentConfig(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "environmentconfigs",
        "scope": "Cluster",
        "status": False,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["EnvironmentConfig"]:
            return EnvironmentConfig

        def build(self) -> "EnvironmentConfig":
            return EnvironmentConfig(**self._attrs)

        def api_version(self, value: Literal["apiextensions.crossplane.io/v1beta1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def data(self, value: dict[str, dict[str, Any]] | None, /) -> Self:
            "The data of this EnvironmentConfig.\nThis may contain any kind of structure that can be serialized into JSON."
            return self._set("data", value)

        def kind(self, value: Literal["EnvironmentConfig"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(
            self, value_or_callback: ObjectMeta | None, /
        ) -> "EnvironmentConfig.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "EnvironmentConfig.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

    class BuilderContext(BuilderContextBase["EnvironmentConfig.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = EnvironmentConfig.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for EnvironmentConfig."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["EnvironmentConfig", Builder]:
        return GenericListBuilder[EnvironmentConfig, EnvironmentConfig.Builder]()

    api_version: Annotated[
        Literal["apiextensions.crossplane.io/v1beta1"], Field(alias="apiVersion")
    ] = "apiextensions.crossplane.io/v1beta1"
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    data: dict[str, dict[str, Any]] | None = None
    "The data of this EnvironmentConfig.\nThis may contain any kind of structure that can be serialized into JSON."
    kind: Literal["EnvironmentConfig"] = "EnvironmentConfig"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None


class UsageSpecByResourceRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageSpecByResourceRef"]:
            return UsageSpecByResourceRef

        def build(self) -> "UsageSpecByResourceRef":
            return UsageSpecByResourceRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Name of the referent."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["UsageSpecByResourceRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageSpecByResourceRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageSpecByResourceRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageSpecByResourceRef", Builder]:
        return GenericListBuilder[UsageSpecByResourceRef, UsageSpecByResourceRef.Builder]()

    name: str
    "Name of the referent."


class UsageSpecByResourceSelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageSpecByResourceSelector"]:
            return UsageSpecByResourceSelector

        def build(self) -> "UsageSpecByResourceSelector":
            return UsageSpecByResourceSelector(**self._attrs)

        def match_controller_ref(self, value: bool | None, /) -> Self:
            "MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
            return self._set("match_controller_ref", value)

        def match_labels(self, value: dict[str, str] | None, /) -> Self:
            "MatchLabels ensures an object with matching labels is selected."
            return self._set("match_labels", value)

    class BuilderContext(BuilderContextBase["UsageSpecByResourceSelector.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageSpecByResourceSelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageSpecByResourceSelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageSpecByResourceSelector", Builder]:
        return GenericListBuilder[
            UsageSpecByResourceSelector, UsageSpecByResourceSelector.Builder
        ]()

    match_controller_ref: Annotated[bool | None, Field(alias="matchControllerRef")] = None
    "MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
    match_labels: Annotated[dict[str, str] | None, Field(alias="matchLabels")] = None
    "MatchLabels ensures an object with matching labels is selected."


class UsageSpecOfResourceRef(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageSpecOfResourceRef"]:
            return UsageSpecOfResourceRef

        def build(self) -> "UsageSpecOfResourceRef":
            return UsageSpecOfResourceRef(**self._attrs)

        def name(self, value: str, /) -> Self:
            "Name of the referent."
            return self._set("name", value)

    class BuilderContext(BuilderContextBase["UsageSpecOfResourceRef.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageSpecOfResourceRef.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageSpecOfResourceRef."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageSpecOfResourceRef", Builder]:
        return GenericListBuilder[UsageSpecOfResourceRef, UsageSpecOfResourceRef.Builder]()

    name: str
    "Name of the referent."


class UsageSpecOfResourceSelector(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageSpecOfResourceSelector"]:
            return UsageSpecOfResourceSelector

        def build(self) -> "UsageSpecOfResourceSelector":
            return UsageSpecOfResourceSelector(**self._attrs)

        def match_controller_ref(self, value: bool | None, /) -> Self:
            "MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
            return self._set("match_controller_ref", value)

        def match_labels(self, value: dict[str, str] | None, /) -> Self:
            "MatchLabels ensures an object with matching labels is selected."
            return self._set("match_labels", value)

    class BuilderContext(BuilderContextBase["UsageSpecOfResourceSelector.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageSpecOfResourceSelector.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageSpecOfResourceSelector."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageSpecOfResourceSelector", Builder]:
        return GenericListBuilder[
            UsageSpecOfResourceSelector, UsageSpecOfResourceSelector.Builder
        ]()

    match_controller_ref: Annotated[bool | None, Field(alias="matchControllerRef")] = None
    "MatchControllerRef ensures an object with the same controller reference\nas the selecting object is selected."
    match_labels: Annotated[dict[str, str] | None, Field(alias="matchLabels")] = None
    "MatchLabels ensures an object with matching labels is selected."


class UsageStatusConditionsItem(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageStatusConditionsItem"]:
            return UsageStatusConditionsItem

        def build(self) -> "UsageStatusConditionsItem":
            return UsageStatusConditionsItem(**self._attrs)

        def last_transition_time(self, value: AwareDatetime, /) -> Self:
            "LastTransitionTime is the last time this condition transitioned from one\nstatus to another."
            return self._set("last_transition_time", value)

        def message(self, value: str | None, /) -> Self:
            "A Message containing details about this condition\u0027s last transition from\none status to another, if any."
            return self._set("message", value)

        def observed_generation(self, value: int | None, /) -> Self:
            "ObservedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
            return self._set("observed_generation", value)

        def reason(self, value: str, /) -> Self:
            "A Reason for this condition\u0027s last transition from one status to another."
            return self._set("reason", value)

        def status(self, value: str, /) -> Self:
            "Status of this condition; is it currently True, False, or Unknown?"
            return self._set("status", value)

        def type(self, value: str, /) -> Self:
            "Type of this condition. At most one of each condition type may apply to\na resource at any point in time."
            return self._set("type", value)

    class BuilderContext(BuilderContextBase["UsageStatusConditionsItem.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageStatusConditionsItem.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageStatusConditionsItem."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageStatusConditionsItem", Builder]:
        return GenericListBuilder[UsageStatusConditionsItem, UsageStatusConditionsItem.Builder]()

    last_transition_time: Annotated[AwareDatetime, Field(alias="lastTransitionTime")]
    "LastTransitionTime is the last time this condition transitioned from one\nstatus to another."
    message: str | None = None
    "A Message containing details about this condition\u0027s last transition from\none status to another, if any."
    observed_generation: Annotated[int | None, Field(alias="observedGeneration")] = None
    "ObservedGeneration represents the .metadata.generation that the condition was set based upon.\nFor instance, if .metadata.generation is currently 12, but the .status.conditions[x].observedGeneration is 9, the condition is out of date\nwith respect to the current state of the instance."
    reason: str
    "A Reason for this condition\u0027s last transition from one status to another."
    status: str
    "Status of this condition; is it currently True, False, or Unknown?"
    type: str
    "Type of this condition. At most one of each condition type may apply to\na resource at any point in time."


class UsageStatus(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageStatus"]:
            return UsageStatus

        def build(self) -> "UsageStatus":
            return UsageStatus(**self._attrs)

        @overload
        def conditions(
            self, value_or_callback: list[UsageStatusConditionsItem] | None, /
        ) -> "UsageStatus.Builder": ...

        @overload
        def conditions(
            self,
            value_or_callback: Callable[
                [GenericListBuilder[UsageStatusConditionsItem, UsageStatusConditionsItem.Builder]],
                GenericListBuilder[UsageStatusConditionsItem, UsageStatusConditionsItem.Builder]
                | list[UsageStatusConditionsItem],
            ],
            /,
        ) -> "UsageStatus.Builder": ...

        @overload
        def conditions(
            self, value_or_callback: Never = ...
        ) -> ListBuilderContext[UsageStatusConditionsItem.Builder]: ...

        def conditions(self, value_or_callback=UNSET, /):
            "Conditions of the resource."
            if self._in_context and value_or_callback is UNSET:
                context = ListBuilderContext[UsageStatusConditionsItem.Builder]()
                context._parent_builder = self
                context._field_name = "conditions"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageStatusConditionsItem.list_builder())
                if isinstance(output, GenericListBuilder):
                    value = output.build()
                else:
                    value = output
            return self._set("conditions", value)

    class BuilderContext(BuilderContextBase["UsageStatus.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageStatus.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageStatus."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageStatus", Builder]:
        return GenericListBuilder[UsageStatus, UsageStatus.Builder]()

    conditions: list[UsageStatusConditionsItem] | None = None
    "Conditions of the resource."


class UsageSpecBy(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageSpecBy"]:
            return UsageSpecBy

        def build(self) -> "UsageSpecBy":
            return UsageSpecBy(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def resource_ref(
            self, value_or_callback: UsageSpecByResourceRef | None, /
        ) -> "UsageSpecBy.Builder": ...

        @overload
        def resource_ref(
            self,
            value_or_callback: Callable[
                [UsageSpecByResourceRef.Builder],
                UsageSpecByResourceRef.Builder | UsageSpecByResourceRef,
            ],
            /,
        ) -> "UsageSpecBy.Builder": ...

        @overload
        def resource_ref(
            self, value_or_callback: Never = ...
        ) -> "UsageSpecByResourceRef.BuilderContext": ...

        def resource_ref(self, value_or_callback=UNSET, /):
            "Reference to the resource."
            if self._in_context and value_or_callback is UNSET:
                context = UsageSpecByResourceRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageSpecByResourceRef.builder())
                if isinstance(output, UsageSpecByResourceRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_ref", value)

        @overload
        def resource_selector(
            self, value_or_callback: UsageSpecByResourceSelector | None, /
        ) -> "UsageSpecBy.Builder": ...

        @overload
        def resource_selector(
            self,
            value_or_callback: Callable[
                [UsageSpecByResourceSelector.Builder],
                UsageSpecByResourceSelector.Builder | UsageSpecByResourceSelector,
            ],
            /,
        ) -> "UsageSpecBy.Builder": ...

        @overload
        def resource_selector(
            self, value_or_callback: Never = ...
        ) -> "UsageSpecByResourceSelector.BuilderContext": ...

        def resource_selector(self, value_or_callback=UNSET, /):
            "Selector to the resource.\nThis field will be ignored if ResourceRef is set."
            if self._in_context and value_or_callback is UNSET:
                context = UsageSpecByResourceSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageSpecByResourceSelector.builder())
                if isinstance(output, UsageSpecByResourceSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_selector", value)

    class BuilderContext(BuilderContextBase["UsageSpecBy.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageSpecBy.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageSpecBy."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageSpecBy", Builder]:
        return GenericListBuilder[UsageSpecBy, UsageSpecBy.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    kind: str | None = None
    "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    resource_ref: Annotated[UsageSpecByResourceRef | None, Field(alias="resourceRef")] = None
    "Reference to the resource."
    resource_selector: Annotated[
        UsageSpecByResourceSelector | None, Field(alias="resourceSelector")
    ] = None
    "Selector to the resource.\nThis field will be ignored if ResourceRef is set."


class UsageSpecOf(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageSpecOf"]:
            return UsageSpecOf

        def build(self) -> "UsageSpecOf":
            return UsageSpecOf(**self._attrs)

        def api_version(self, value: str | None, /) -> Self:
            "API version of the referent."
            return self._set("api_version", value)

        def kind(self, value: str | None, /) -> Self:
            "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def resource_ref(
            self, value_or_callback: UsageSpecOfResourceRef | None, /
        ) -> "UsageSpecOf.Builder": ...

        @overload
        def resource_ref(
            self,
            value_or_callback: Callable[
                [UsageSpecOfResourceRef.Builder],
                UsageSpecOfResourceRef.Builder | UsageSpecOfResourceRef,
            ],
            /,
        ) -> "UsageSpecOf.Builder": ...

        @overload
        def resource_ref(
            self, value_or_callback: Never = ...
        ) -> "UsageSpecOfResourceRef.BuilderContext": ...

        def resource_ref(self, value_or_callback=UNSET, /):
            "Reference to the resource."
            if self._in_context and value_or_callback is UNSET:
                context = UsageSpecOfResourceRef.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_ref"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageSpecOfResourceRef.builder())
                if isinstance(output, UsageSpecOfResourceRef.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_ref", value)

        @overload
        def resource_selector(
            self, value_or_callback: UsageSpecOfResourceSelector | None, /
        ) -> "UsageSpecOf.Builder": ...

        @overload
        def resource_selector(
            self,
            value_or_callback: Callable[
                [UsageSpecOfResourceSelector.Builder],
                UsageSpecOfResourceSelector.Builder | UsageSpecOfResourceSelector,
            ],
            /,
        ) -> "UsageSpecOf.Builder": ...

        @overload
        def resource_selector(
            self, value_or_callback: Never = ...
        ) -> "UsageSpecOfResourceSelector.BuilderContext": ...

        def resource_selector(self, value_or_callback=UNSET, /):
            "Selector to the resource.\nThis field will be ignored if ResourceRef is set."
            if self._in_context and value_or_callback is UNSET:
                context = UsageSpecOfResourceSelector.BuilderContext()
                context._parent_builder = self
                context._field_name = "resource_selector"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageSpecOfResourceSelector.builder())
                if isinstance(output, UsageSpecOfResourceSelector.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("resource_selector", value)

    class BuilderContext(BuilderContextBase["UsageSpecOf.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageSpecOf.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageSpecOf."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageSpecOf", Builder]:
        return GenericListBuilder[UsageSpecOf, UsageSpecOf.Builder]()

    api_version: Annotated[str | None, Field(alias="apiVersion")] = None
    "API version of the referent."
    kind: str | None = None
    "Kind of the referent.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    resource_ref: Annotated[UsageSpecOfResourceRef | None, Field(alias="resourceRef")] = None
    "Reference to the resource."
    resource_selector: Annotated[
        UsageSpecOfResourceSelector | None, Field(alias="resourceSelector")
    ] = None
    "Selector to the resource.\nThis field will be ignored if ResourceRef is set."


class UsageSpec(BaseModel):
    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["UsageSpec"]:
            return UsageSpec

        def build(self) -> "UsageSpec":
            return UsageSpec(**self._attrs)

        @overload
        def by(self, value_or_callback: UsageSpecBy | None, /) -> "UsageSpec.Builder": ...

        @overload
        def by(
            self,
            value_or_callback: Callable[[UsageSpecBy.Builder], UsageSpecBy.Builder | UsageSpecBy],
            /,
        ) -> "UsageSpec.Builder": ...

        @overload
        def by(self, value_or_callback: Never = ...) -> "UsageSpecBy.BuilderContext": ...

        def by(self, value_or_callback=UNSET, /):
            'By is the resource that is "using the other resource".'
            if self._in_context and value_or_callback is UNSET:
                context = UsageSpecBy.BuilderContext()
                context._parent_builder = self
                context._field_name = "by"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageSpecBy.builder())
                if isinstance(output, UsageSpecBy.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("by", value)

        @overload
        def of(self, value_or_callback: UsageSpecOf, /) -> "UsageSpec.Builder": ...

        @overload
        def of(
            self,
            value_or_callback: Callable[[UsageSpecOf.Builder], UsageSpecOf.Builder | UsageSpecOf],
            /,
        ) -> "UsageSpec.Builder": ...

        @overload
        def of(self, value_or_callback: Never = ...) -> "UsageSpecOf.BuilderContext": ...

        def of(self, value_or_callback=UNSET, /):
            'Of is the resource that is "being used".'
            if self._in_context and value_or_callback is UNSET:
                context = UsageSpecOf.BuilderContext()
                context._parent_builder = self
                context._field_name = "of"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageSpecOf.builder())
                if isinstance(output, UsageSpecOf.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("of", value)

        def reason(self, value: str | None, /) -> Self:
            "Reason is the reason for blocking deletion of the resource."
            return self._set("reason", value)

        def replay_deletion(self, value: bool | None, /) -> Self:
            "ReplayDeletion will trigger a deletion on the used resource during the deletion of the usage itself, if it was attempted to be deleted at least once."
            return self._set("replay_deletion", value)

    class BuilderContext(BuilderContextBase["UsageSpec.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = UsageSpec.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for UsageSpec."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["UsageSpec", Builder]:
        return GenericListBuilder[UsageSpec, UsageSpec.Builder]()

    by: UsageSpecBy | None = None
    'By is the resource that is "using the other resource".'
    of: UsageSpecOf
    'Of is the resource that is "being used".'
    reason: str | None = None
    "Reason is the reason for blocking deletion of the resource."
    replay_deletion: Annotated[bool | None, Field(alias="replayDeletion")] = None
    "ReplayDeletion will trigger a deletion on the used resource during the deletion of the usage itself, if it was attempted to be deleted at least once."


class Usage(Resource):
    __cloudcoil_api__: ClassVar[dict] = {
        "plural": "usages",
        "scope": "Cluster",
        "status": True,
    }

    class Builder(BaseModelBuilder):
        @property
        def cls(self) -> type["Usage"]:
            return Usage

        def build(self) -> "Usage":
            return Usage(**self._attrs)

        def api_version(self, value: Literal["apiextensions.crossplane.io/v1beta1"], /) -> Self:
            "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
            return self._set("api_version", value)

        def kind(self, value: Literal["Usage"], /) -> Self:
            "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
            return self._set("kind", value)

        @overload
        def metadata(self, value_or_callback: ObjectMeta | None, /) -> "Usage.Builder": ...

        @overload
        def metadata(
            self,
            value_or_callback: Callable[[ObjectMeta.Builder], ObjectMeta.Builder | ObjectMeta],
            /,
        ) -> "Usage.Builder": ...

        @overload
        def metadata(self, value_or_callback: Never = ...) -> "ObjectMeta.BuilderContext": ...

        def metadata(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = ObjectMeta.BuilderContext()
                context._parent_builder = self
                context._field_name = "metadata"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(ObjectMeta.builder())
                if isinstance(output, ObjectMeta.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("metadata", value)

        @overload
        def spec(self, value_or_callback: UsageSpec, /) -> "Usage.Builder": ...

        @overload
        def spec(
            self,
            value_or_callback: Callable[[UsageSpec.Builder], UsageSpec.Builder | UsageSpec],
            /,
        ) -> "Usage.Builder": ...

        @overload
        def spec(self, value_or_callback: Never = ...) -> "UsageSpec.BuilderContext": ...

        def spec(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = UsageSpec.BuilderContext()
                context._parent_builder = self
                context._field_name = "spec"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageSpec.builder())
                if isinstance(output, UsageSpec.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("spec", value)

        @overload
        def status(self, value_or_callback: UsageStatus | None, /) -> "Usage.Builder": ...

        @overload
        def status(
            self,
            value_or_callback: Callable[[UsageStatus.Builder], UsageStatus.Builder | UsageStatus],
            /,
        ) -> "Usage.Builder": ...

        @overload
        def status(self, value_or_callback: Never = ...) -> "UsageStatus.BuilderContext": ...

        def status(self, value_or_callback=UNSET, /):
            if self._in_context and value_or_callback is UNSET:
                context = UsageStatus.BuilderContext()
                context._parent_builder = self
                context._field_name = "status"
                return context

            if value_or_callback is UNSET:
                raise TypeError("A value is required outside a builder context")
            value = value_or_callback
            if callable(value_or_callback):
                output = value_or_callback(UsageStatus.builder())
                if isinstance(output, UsageStatus.Builder):
                    value = output.build()
                else:
                    value = output
            return self._set("status", value)

    class BuilderContext(BuilderContextBase["Usage.Builder"]):
        def model_post_init(self, __context) -> None:
            self._builder = Usage.Builder()
            self._builder._in_context = True
            self._parent_builder = None
            self._field_name = None

    @classmethod
    def builder(cls) -> Builder:
        return cls.Builder()

    @classmethod
    def new(cls) -> BuilderContext:
        """Creates a new context manager builder for Usage."""
        return cls.BuilderContext()

    @classmethod
    def list_builder(cls) -> GenericListBuilder["Usage", Builder]:
        return GenericListBuilder[Usage, Usage.Builder]()

    api_version: Annotated[
        Literal["apiextensions.crossplane.io/v1beta1"], Field(alias="apiVersion")
    ] = "apiextensions.crossplane.io/v1beta1"
    "APIVersion defines the versioned schema of this representation of an object.\nServers should convert recognized schemas to the latest internal value, and\nmay reject unrecognized values.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources"
    kind: Literal["Usage"] = "Usage"
    "Kind is a string value representing the REST resource this object represents.\nServers may infer this from the endpoint the client submits requests to.\nCannot be updated.\nIn CamelCase.\nMore info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds"
    metadata: ObjectMeta | None = None
    spec: UsageSpec
    status: UsageStatus | None = None
